"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTH_USER_MODEL

# from django.conf.global_settings import STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%mf#xayv&ve(b4kc27o#08p)d6mjg$6cmnv=xtim%kpyb*$o_a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # для отображения ошибок на сервере разработчику

ALLOWED_HOSTS = []  # указывается, на каких хостах будет работать дебаг

# Application definition

INSTALLED_APPS = [  # установленные приложения
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres', # приложение для полнотекстового поиска в базе данных

    "debug_toolbar",

    'main',
    'goods',
    'users',
    'carts',
    'testCart',

]

MIDDLEWARE = [  # промежуточные программные обеспечения
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'app.urls'  # переменная указывает на файл, в котором есть все адреса сайта

TEMPLATES = [  # шаблонизатор, отвечающий за наполнение и прорисовку html страниц
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],  # дополнительные пути, где искать шаблоны
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


DATABASES = {
    'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': BASE_DIR / 'db.sqlite3',
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "market",
        "USER": "postgres",
        "PASSWORD": "1234",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


AUTH_PASSWORD_VALIDATORS = [  # валидаторы пароля
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'ru-ru'  # перевод админ панели

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'  # перфикс для URL адреса статических файлов

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/' # перфикс для media адреса

MEDIA_ROOT = BASE_DIR/'media'

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # автоматическая инкреминтация (для создания id в таблице)
AUTH_USER_MODEL = 'users.User' # указываем, какую модель использовать вместо AuthUser (приложение.Модель)